wtf/models.py
# coding: utf-8
from .db import db


class Noticia(db.Document):
    titulo = db.StringField(required=True)
    texto = db.StringField(required=True)
    imagem = db.StringField()

wtf/__init__.py
# just an init file

wtf/blueprints/noticias.py
# coding: utf-8
import os
from werkzeug import secure_filename
from flask import (
    Blueprint, request, current_app, send_from_directory, render_template
)
from ..models import Noticia
from ..cache import cache
from flask_security import login_required

noticias_blueprint = Blueprint('noticias', __name__)


@noticias_blueprint.route("/noticias/cadastro", methods=["GET", "POST"])
@login_required
def cadastro():
    if request.method == "POST":
        dados_do_formulario = request.form.to_dict()
        if not all([dados_do_formulario['titulo'],
                    dados_do_formulario['texto']]):
            return render_template('error.html', error=u"Campos obrigatórios")
        imagem = request.files.get('imagem')
        if imagem:
            filename = secure_filename(imagem.filename)
            path = os.path.join(current_app.config['MEDIA_ROOT'], filename)
            imagem.save(path)
            dados_do_formulario['imagem'] = filename
        nova_noticia = Noticia.objects.create(**dados_do_formulario)
        # limpa o cache sempre que add nova noticia
        cache.clear()
        return render_template('cadastro_sucesso.html',
                               id_nova_noticia=nova_noticia.id)
    return render_template('cadastro.html', title=u"Inserir nova noticia")


@noticias_blueprint.route("/")
@cache.cached(timeout=300)
def index():
    todas_as_noticias = Noticia.objects.all()
    return render_template('index.html',
                           noticias=todas_as_noticias,
                           title=u"Todas as notícias")


@noticias_blueprint.route("/noticia/<noticia_id>")
def noticia(noticia_id):
    noticia_cacheada = cache.get(noticia_id)
    if noticia_cacheada:
        noticia = noticia_cacheada
    else:
        noticia = Noticia.objects.get(id=noticia_id)
        cache.set(noticia_id, noticia, timeout=300)
    return render_template('noticia.html', noticia=noticia)


@noticias_blueprint.route('/media/<path:filename>')
def media(filename):
    return send_from_directory(current_app.config.get('MEDIA_ROOT'), filename)

wtf/templates/admin_base.html
{% extends 'admin/base.html' %}

{% block access_control %}
<div class="navbar-text btn-group pull-right">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <i class="glyphicon glyphicon-user"></i>
    {% if current_user.is_authenticated and not current_user.is_anonymous %}
        {% if current_user.name -%}
            {{ current_user.name }}
        {% else -%}
            {{ current_user.email }}
        {%- endif %}
    <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
       <li><a href="{{url_for_security('logout')}}">Log out</a></li>
    </ul>
    {% else %}
       Access
       <span class="caret"></span></a>
       <ul class="dropdown-menu" role="menu">
           <li><a href="{{url_for_security('login')}}">Login</a></li>
        </ul>
    {% endif %}
</div>
{% endblock %}

wtf/templates/base.html
{%- extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}
{% block title %} {{title or "Notícias"}} {% endblock %}
{% block navbar -%}
    <nav class="navbar navbar-default">
       <a class="navbar-brand" href="#"><img src="{{url_for('static', filename='generic_logo.gif')}}" style="height:30px;"></a>
       <ul class="nav navbar-nav">
         <li><a href="{{url_for('noticias.index')}}">HOME</a> </li>
         <li><a href="{{url_for('noticias.cadastro')}}">CADASTRO</a></li>
         {% block access_control %}
            <li class="divider-vertical"></li>
            {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 {{current_user.email}}  <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                  <li><a href="{{url_for_security('change_password')}}"><i class="icon-user"></i> Change password</a></li>
                  <li><a href="{{url_for_security('logout')}}"><i class="icon-off"></i> Logout</a></li>
              </ul>
            </li>
            {% else %}
              <li><a href="{{url_for_security('login')}}"><i class="icon-off"></i> Login</a></li>
            {% endif %}
        {% endblock %}
       </ul>
    </nav>
{%- endblock navbar %}
{% block content %}
 <div class="container">
  {%- with messages = get_flashed_messages(with_categories=True) %}
  {%- if messages %}
    <div class="row">
      <div class="col-md-12">
        {{utils.flashed_messages(messages)}}
      </div>
    </div>
  {%- endif %}
  {%- endwith %}
    <div class="jumbotron">
      {% block news %}
      {% endblock %}
    </div>
{%- endblock content%}

wtf/templates/cadastro.html
{% extends "base.html" %}
{% block news %}
<form method="post" action="{{ url_for('noticias.cadastro') }}" enctype="multipart/form-data">
   <label>Titulo:<br />
        <input type="text" name="titulo" id="titulo" />
   </label>
   <br />
   <label>Texto:<br />
        <textarea name="texto" id="texto"></textarea>
   </label>
   <br />
   <label> Imagem:<br />
      <input type="file" name="imagem" id="imagem" />
   </label>
   <input type="submit" value="Postar" />
</form>
{% endblock %}

wtf/templates/cadastro_sucesso.html
{% extends "base.html" %}
{% block title %}
    Notícia {{id_nova_noticia}} inserida com sucesso
{% endblock %}

{% block news %}
    <h1>Notícia {{id_nova_noticia}} inserida com sucesso!</h1>
    <a href="{{url_for('noticias.noticia', noticia_id=id_nova_noticia)}}"> Ler Notícia </a><br />
    <a href="{{url_for('noticias.cadastro')}}"> Cadastrar nova notícia </a>
{% endblock %}

wtf/templates/error.html
{% extends "base.html" %}
{% block title%}
    Erro
{% endblock%}

{% block news %}
    <h1>Ocorreu um Erro!</h1>
    {{  error }}
{% endblock %}

wtf/templates/index.html
{% extends "base.html" %}
{% block news %}
<h2>Todas as notícias</h2>
<ul>
    {% for noticia in noticias %}
    <li>
        <a href="{{url_for('noticias.noticia', noticia_id=noticia.id)}}">
         {{noticia.titulo}}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

wtf/templates/noticia.html
{% extends "base.html" %}
{% block title%}
    {{noticia.titulo}}
{% endblock%}

{% block news %}
    <h1>{{noticia.titulo}}</h1>
    {% if noticia.imagem %}
        <img src="{{ url_for('noticias.media', filename=noticia.imagem) }}" width="300" />
    {% endif %}
    <hr />
    <p>
        {{noticia.texto|safe}}
    </p>
{% endblock %}